version: '3.7'
services:
    dbpg:
        image: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432
        volumes: 
          # copy the sql script to create tables
          - ./seed/full.sql:/docker-entrypoint-initdb.d/full.sql
    adminer:
      image: adminer
      restart: always
      ports:
        - 8000:8080
      depends_on:
        - dbpg
    web-node:
        build: .
        ports:
          - 8080:8080
        environment:
          - PGUSER=postgres
          - PGDATABASE=pa
          - PGHOST=dbpg
          - PGPASSWORD=postgres
          - PGPORT=5432
        depends_on:
          - dbpg
